### PR TITLE
Update proposal for mkdocs, causal-cmd documentation

### PR DESCRIPTION
**Pull request by yasu-sh**
As I mentioned at #17, I have a proposal to update document about two months ago. I hope the owner of this repo accepts this modification. 
python version is also outdated, so I tried to use latest mkdocs with supported python version.

I added py-causal and r-causal current status also so as to the copy of the tetrad's github repo.

### CODE REVIEW

**Comment by jdramsey** [comment]
@yasu-sh I'm not sure who exactly has access to this repository. I guess I could ask.

**Comment by yasu-sh** [comment]
@jdramsey Thanks a lot for checking current status!

**Comment by yasu-sh** [comment]
@jdramsey Could you tell me what I can do for this PR to move on to the next?
I think this page helps users. Hopefully I have something to contribute.

**Comment by jdramsey** [comment]
@yasu-sh I'm so sorry, I've been so busy I'm afraid I've been losing track of threads. I'm not sure what to do about this exactly, but I'll try to find out.

**Comment by yasu-sh** [comment]
@jdramsey Thanks for your reply. I know some developers must have referred this manual even the documents are somewhat old.
I have just followed the instruction in README.md. I was in staging. In this case you might need to accept 2 PRs. i.e. stage-docs.

But if you are not certain, I can give up on this.

**Comment by jdramsey** [comment]
I would do it right away if I had access. I don't know who has access to that anymore. Let me write to a couple of people.

**Comment by yasu-sh** [comment]
@kvb2univpitt As @jdramsey [informed me](https://github.com/cmu-phil/py-tetrad/issues/1#issuecomment-1743655108), I would like your support for me to contribute this documents.
I would like to check my update after accepting this PR since this is for "staging" subfolder. 
Staging web site to be checked: https://bd2kccd.github.io/stage/ 

After you or @jdramsey checked, official release can be done by me or you(any contributors).
i.e. https://github.com/bd2kccd/bd2kccd.github.io#8-sending-a-pull-request-for-changes-review

Final web site https://bd2kccd.github.io/docs/

**Comment by kvb2univpitt** [comment]
@yasu-sh Sorry for the late reply.  I have been sick lately and wasn't able to do much work.

Thank you very much for helping out with the documentation.  Your help is very much appreciated!  I will merge this pull request.

**Pull request merged**
